import test from 'node:test';
import assert from 'node:assert/strict';
import { BoxGeometry, Mesh, MeshStandardMaterial, Group, Raycaster, Vector3 } from 'three';
import { applyStreetOpenings } from '../src/world/street-openings.mjs';

test('highway openings remove actual sidewalk and curb geometry and restore when removed', () => {
  const geometry = new BoxGeometry(10, 0.2, 2);
  const mesh = new Mesh(geometry, new MeshStandardMaterial());
  mesh.userData.streetCuttable = true;
  const group = new Group();
  group.add(mesh);
  group.updateMatrixWorld(true);
  const cuts = [{ minX: -0.3, maxX: 0.3, minZ: -2, maxZ: 2 }];
  const ray = (x) => new Raycaster(new Vector3(x, 2, 0), new Vector3(0, -1, 0));
  assert.ok(ray(0.07).intersectObject(mesh).length);
  applyStreetOpenings(group, cuts);
  assert.equal(ray(0.07).intersectObject(mesh).length, 0);
  assert.ok(ray(0.7).intersectObject(mesh).length);
  const side = new Raycaster(new Vector3(0.07, 0, 3), new Vector3(0, 0, -1));
  assert.equal(side.intersectObject(mesh).length, 0);
  const count = mesh.geometry.attributes.position.count;
  const retained = mesh.geometry;
  let disposed = 0;
  retained.addEventListener('dispose', () => disposed++);
  applyStreetOpenings(group, structuredClone(cuts));
  assert.equal(mesh.geometry, retained);
  assert.equal(disposed, 0);
  assert.equal(mesh.geometry.attributes.position.count, count);
  assert.equal(mesh.geometry.attributes.uv.count, count);
  assert.equal(mesh.geometry.attributes.normal.count, count);
  assert.ok([...mesh.geometry.attributes.position.array].every(Number.isFinite));
  applyStreetOpenings(group, [{ minX: 0.5, maxX: 1, minZ: -2, maxZ: 2 }]);
  assert.equal(disposed, 1);
  assert.ok(ray(0.07).intersectObject(mesh).length);
  assert.equal(ray(0.7).intersectObject(mesh).length, 0);
  applyStreetOpenings(group, []);
  assert.equal(mesh.geometry, geometry);
  assert.ok(ray(0.07).intersectObject(mesh).length);
  geometry.dispose();
  mesh.material.dispose();
});
